[package]
name = "mcclankattack"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
chrono = "0.4.42"
fastrand = "2.3.0"
flate2 = "1.1.5"
md5 = "0.8.0"
tokio = { version = "1.48.0", features = ["full"] }
